---
language: python
python:
  - 3.8

before_install:
  - pip install --user --upgrade pipenv

install:
  - pipenv install
  - pip install --user --upgrade flake8

script:
  - flake8 --statistics --verbose *.py
